# Generated by Django 5.2.14 on 2026-06-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(max_length=10)),
                ('passenger_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
