# Generated by Django 5.2.14 on 2026-06-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bus_name',
            field=models.CharField(default='Unknown Bus', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='journey_date',
            field=models.CharField(default='Unknown Date', max_length=20),
            preserve_default=False,
        ),
    ]
