# Generated by Django 5.2.14 on 2026-06-04 04:35

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_booking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=myapp.models.generate_booking_id, max_length=20, unique=True),
        ),
    ]
