# Generated by Django 5.2.14 on 2026-06-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_booking_boarding_point_booking_boarding_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='boarding_point',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='drop_point',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passenger_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_no',
            field=models.TextField(),
        ),
    ]
