# Generated by Django 5.2.14 on 2026-06-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_bus_bus_type_bus_fare_bus_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='arrival_time',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bus',
            name='departure_time',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bus',
            name='driver_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bus',
            name='driver_phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='bus',
            name='fare',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bus',
            name='route',
            field=models.TextField(default=''),
        ),
    ]
