# Generated by Django 5.2.14 on 2026-06-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_complaint_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='eta',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bus',
            name='latitude',
            field=models.FloatField(default=12.9716),
        ),
        migrations.AddField(
            model_name='bus',
            name='longitude',
            field=models.FloatField(default=77.5946),
        ),
        migrations.AddField(
            model_name='bus',
            name='next_stop',
            field=models.CharField(default='', max_length=100),
        ),
    ]
