# Generated by Django 5.2.14 on 2026-06-09 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_bus_eta_bus_latitude_bus_longitude_bus_next_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.bus'),
        ),
    ]
