# Generated by Django 5.2.14 on 2026-06-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
